"""
Manipulate AnsMath vectors or dense matrices as NumPy arrays
------------------------------------------------------------
This example demonstrates how to use NumPy arrays to exchange data between PyAnsys Math
and Python.

.. note::
    This example requires Ansys 2021R2.

"""
import matplotlib.pyplot as plt
import numpy as np

import ansys.math.core.math as pymath

# Start PyAnsys Math.
mm = pymath.AnsMath()


###############################################################################
# Convert an AnsMath vector into an NumPy array.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# First, allocate an AnsMath vector with 10 doubles

apdl_vec = mm.ones(10)
print(apdl_vec)

###############################################################################
# Then create an NumPy array from this AnsMath vector.
#
# Note that these are two separate objects: memory is
# duplicated. Modifying one object does not modify its clone.
pv = apdl_vec.asarray()
print(pv)


###############################################################################
# You can then manipulate this NumPy array with all existing NumPy
# features.
pv = (pv + 1) ** 2
print(pv)


###############################################################################
# Alternatively, the AnsMath object can be operated on directly with
# NumPy with the Numpy methods.
print(np.max(apdl_vec))
print(np.linalg.norm(apdl_vec))

###############################################################################
# Note that some methods have APDL corollaries, and these methods are
# more efficient if performed within PyAnsys Math.
#
# For example, the norm method can be performed within PyAnsys Math.
print(apdl_vec.norm(), np.linalg.norm(apdl_vec))

###############################################################################
# Copy a NumPy array to an AnsMath vector.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# You can push back any NumPy vector or 2D array to PyAnsys Math. This
# creates a new AnsMath vector, which in this case is named ``'NewVec'``.
mm.set_vec(pv, "NewVec")
print(mm.status())


###############################################################################
# Create a Python handle to this vector by specifying its name.
v2 = mm.vec(name="NewVec")
print(v2)


###############################################################################
# Dense Numpy arrays.
# ~~~~~~~~~~~~~~~~~~~
# The same features apply to dense APDL matrices and NumPy arrays.
#
# Allocate an AnsMath dense matrix
apdl_mat = mm.rand(3, 3)
plt.imshow(apdl_mat, cmap="YlOrBr")
plt.colorbar()
plt.title("AnsMath dense matrix")
plt.show()

###############################################################################
# Convert it to a NumPy array.

np_arr = apdl_mat.asarray()

assert np.allclose(apdl_mat, np_arr)
print(apdl_mat)
print(np_arr)

###############################################################################
# You can load NumPy array to APDL with the matrix method.
np_rand = np.random.random((4, 4))
ans_mat = mm.matrix(np_rand)

# print the autogenerated name of the this matrix
print(ans_mat.id)


###############################################################################
# Load this matrix from APDL and verify it is identical.
from_ans = ans_mat.asarray()
print(np.allclose(from_ans, np_rand))


###############################################################################
# Stop PyAnsys Math.

mm._mapdl.exit()
